const drinks=[["☕","咖啡"],["♨","茶"],["🧋","奶茶"],["🥛","牛奶"],["💧","矿泉水"],["🍊","果汁"],["🥤","汽水"],["🍶","酸奶"]];
const moods=[["☀","愉悦"],["◌","焦虑"],["☾","疲惫"],["◇","迷茫"],["✧","平静"],["♢","低落"],["⚡","兴奋"]];
const cards=["愚者","魔术师","女祭司","皇后","皇帝","教皇","恋人","战车","力量","隐者","命运之轮","正义","倒吊人","死神","节制","恶魔","高塔","星星","月亮","太阳","审判","世界","权杖王牌","圣杯王牌","宝剑王牌","星币王牌"];
const symbols=["✹","✺","☽","♛","♜","♗","♡","▣","♞","☿","◉","⚖","◒","✦","◌","⛓","⚡","✦","☾","☼","♧","◎","🔥","♔","⚔","◈"];const state={drink:null,mood:null};let lastSpread=null;const $=s=>document.querySelector(s);
const emptyStats=()=>({started:0,completed:0,shares:0,drinks:{},moods:{}});function readStats(){try{const x=JSON.parse(localStorage.getItem("sipArcanaStats")||"null")||{};return {...emptyStats(),...x,drinks:{...(x.drinks||{})},moods:{...(x.moods||{})}}}catch{return emptyStats()}}function saveStats(s){try{localStorage.setItem("sipArcanaStats",JSON.stringify(s))}catch{}}function renderStats(){const s=readStats(),top=x=>Object.entries(x).sort((a,b)=>b[1]-a[1])[0]?.[0]||"—";[["#topDrink",top(s.drinks)],["#topMood",top(s.moods)],["#completionRate",`${s.started?Math.round(s.completed/s.started*100):0}%`],["#shareCount",s.shares]].forEach(([id,v])=>{const e=$(id);if(e)e.textContent=v})}
function renderChoices(items,id,type){const e=$(id);if(e)e.innerHTML=items.map(([i,l])=>`<button class="choice" data-type="${type}" data-value="${l}" type="button"><span class="choice-icon">${i}</span><span class="choice-label">${l}</span></button>`).join("")}
function draw(){return [0,1,2].map((_,i)=>({name:cards[Math.floor(Math.random()*cards.length)],symbol:symbols[Math.floor(Math.random()*symbols.length)],reversed:Math.random()>.56,role:["当前状态","行动建议","今日结果"][i]}))}function fallback(s){return s.map(c=>`${c.name}${c.reversed?"逆位":"正位"}读取着你选择的${state.drink}与此刻的${state.mood}。这张牌提醒你先承认当下的感受，不必急着证明自己，让注意力回到眼前能够照顾好的小事，今天的方向会在行动中逐渐清晰。`)}
async function getReading(s){const c=new AbortController(),t=setTimeout(()=>c.abort(),25000);try{const r=await fetch("/api/reading",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({drink:state.drink,mood:state.mood,cards:s}),signal:c.signal});if(!r.ok)throw Error();const d=await r.json();if(!Array.isArray(d.sections)||d.sections.length!==3)throw Error();return d.sections}finally{clearTimeout(t)}}
function paint(s){$("#resultMeta").textContent=`${state.drink} · ${state.mood}`;$("#tarotSpread").innerHTML=s.map(c=>`<article class="tarot-card ${c.reversed?"reverse":""}"><div class="tarot-inner"><div class="card-position">${c.role}</div><div class="card-symbol">${c.symbol}</div><div class="card-name">${c.name} · ${c.reversed?"逆位":"正位"}</div></div></article>`).join("")}
async function showResult(s=draw()){lastSpread=s;const st=readStats();st.started++;saveStats(st);renderStats();$("#result").classList.remove("hidden");$("#result").scrollIntoView({behavior:"smooth"});$("#aiStatus").className="ai-status loading";$("#aiStatus").textContent="正在为你整理三张牌之间的线索…";$("#aiStatus").classList.remove("hidden");$("#resultActions").classList.add("hidden");$("#feedback").classList.add("hidden");$("#retryBtn").classList.add("hidden");paint(s);try{const lines=await getReading(s);$("#aiStatus").classList.add("hidden");$("#coreSecret").innerHTML=`<p class="eyebrow">TODAY'S CORE SECRET</p><p>${lines.join(" ").slice(0,150)}…</p>`;$("#coreSecret").classList.remove("hidden");$("#readingCopy").innerHTML=lines.map((x,i)=>`<div class="reading-block"><h3>${s[i].role} · ${s[i].name}</h3><p>${x}</p></div>`).join("");window.currentText=`今日饮见 · ${state.drink} · ${state.mood}\n\n${lines.join("\n\n")}`;$("#resultActions").classList.remove("hidden");$("#feedback").classList.remove("hidden");const done=readStats();done.completed++;saveStats(done);renderStats()}catch(e){const lines=fallback(s);$("#aiStatus").className="ai-status error";$("#aiStatus").textContent="AI 解读暂时无法连接，先为你展示牌面。";$("#readingCopy").innerHTML=lines.map((x,i)=>`<div class="reading-block"><h3>${s[i].role} · ${s[i].name}</h3><p>${x}</p></div>`).join("");window.currentText=`今日饮见 · ${state.drink} · ${state.mood}\n\n${lines.join("\n\n")}`;$("#resultActions").classList.remove("hidden");$("#retryBtn").classList.remove("hidden")}finally{$("#revealBtn").disabled=false;$ ("#revealBtn").textContent="让牌面回应我"}}
function share(){
  const s=readStats();s.shares++;saveStats(s);renderStats();
  const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;
  const ctx=canvas.getContext('2d');
  const gradient=ctx.createLinearGradient(0,0,1080,1350);gradient.addColorStop(0,'#312044');gradient.addColorStop(.52,'#120d1d');gradient.addColorStop(1,'#08070d');ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1350);
  ctx.strokeStyle='rgba(215,179,106,.55)';ctx.lineWidth=3;ctx.strokeRect(46,46,988,1258);
  ctx.fillStyle='#d7b36a';ctx.font='30px serif';ctx.fillText('✦  今日饮见 · SIP & ARCANA',84,122);
  ctx.fillStyle='#f4ede4';ctx.font='48px serif';ctx.fillText(`${state.drink} · ${state.mood}`,84,215);
  ctx.fillStyle='#d7b36a';ctx.font='34px serif';ctx.fillText('今日三牌秘语',84,300);
  document.querySelectorAll('.card-name').forEach((el,i)=>{ctx.fillStyle='#e4c995';ctx.font='30px serif';ctx.fillText(el.textContent,84,400+i*78)});
  const core=document.querySelector('#coreSecret p:last-child')?.textContent||'让今天的回应，成为温柔的方向。';ctx.fillStyle='#c6b9b8';ctx.font='26px serif';(core.slice(0,170).match(/.{1,24}/g)||[]).forEach((line,i)=>ctx.fillText(line,84,710+i*48));
  ctx.fillStyle='#827681';ctx.font='20px serif';ctx.fillText('仅供娱乐与自我探索，不代表确定的未来预测。',84,1245);
  canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob);const link=document.createElement('a');link.download='今日饮见-分享.png';link.href=url;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png');
}
renderChoices(drinks,"#drinkChoices","drink");renderChoices(moods,"#moodChoices","mood");renderStats();document.querySelector("[data-scroll-to=ritual]")?.addEventListener("click",()=>$("#ritual")?.scrollIntoView({behavior:"smooth"}));document.addEventListener("click",e=>{const c=e.target.closest(".choice");if(!c)return;document.querySelectorAll(`[data-type="${c.dataset.type}"]`).forEach(x=>x.classList.remove("selected"));c.classList.add("selected");state[c.dataset.type]=c.dataset.value;const s=readStats(),b=c.dataset.type==="drink"?s.drinks:s.moods;b[c.dataset.value]=(b[c.dataset.value]||0)+1;saveStats(s);renderStats();$("#revealBtn").disabled=!(state.drink&&state.mood)});$("#revealBtn").addEventListener("click",()=>showResult());$("#retryBtn").addEventListener("click",()=>showResult(lastSpread||draw()));$("#copyBtn").addEventListener("click",()=>navigator.clipboard.writeText(window.currentText||""));$("#shareBtn").addEventListener("click",share);$("#restartBtn").addEventListener("click",()=>location.reload());document.querySelectorAll("[data-feedback]").forEach(b=>b.addEventListener("click",()=>{$("#feedbackThanks").textContent=`已记录：${b.dataset.feedback}。感谢你的回应。`;$("#feedbackThanks").classList.remove("hidden")}));
document.querySelectorAll('.mood-heading').forEach((el,index)=>{if(index>0)el.remove()});
