const drinks=[['☕','咖啡'],['♨','茶'],['🧋','奶茶'],['🥛','牛奶'],['💧','矿泉水'],['🍊','果汁'],['🥤','汽水'],['🍶','酸奶']];
const moods=[['☀','愉悦'],['◌','焦虑'],['☾','疲惫'],['◇','迷茫'],['✧','平静'],['♢','低落'],['⚡','兴奋']];
const cards=[['女祭司','☽'],['圣杯女王','♔'],['星星','✦'],['隐者','☿'],['力量','♜'],['节制','◒'],['太阳','☼'],['月亮','☾'],['魔术师','✺'],['世界','◎'],['正义','⚖'],['愚者','✹']];
const state={drink:null,mood:null};
const $=s=>document.querySelector(s);
function renderChoices(items,id,type){$(id).innerHTML=items.map(([icon,label])=>`<button class="choice" data-type="${type}" data-value="${label}" type="button"><span class="choice-icon">${icon}</span><span class="choice-label">${label}</span></button>`).join('')}
renderChoices(drinks,'#drinkChoices','drink');renderChoices(moods,'#moodChoices','mood');
document.addEventListener('click',e=>{const c=e.target.closest('.choice');if(c){document.querySelectorAll(`[data-type="${c.dataset.type}"]`).forEach(x=>x.classList.remove('selected'));c.classList.add('selected');state[c.dataset.type]=c.dataset.value;$('#revealBtn').disabled=!(state.drink&&state.mood)}});
document.querySelectorAll('[data-scroll-to]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.scrollTo).scrollIntoView({behavior:'smooth'})));
function draw(){return Array.from({length:3},(_,i)=>{const [name,symbol]=cards[Math.floor(Math.random()*cards.length)];return {name,symbol,reversed:Math.random()>.56,role:['当前状态','行动建议','今日结果'][i]}})}
function makeReading(spread){const tone={愉悦:'明亮而有余温',焦虑:'敏锐却略显拥挤',疲惫:'需要被温柔托住',迷茫:'正在寻找一条可走的路',平静:'拥有安静的力量',低落:'藏着尚未说出的感受',兴奋:'有一束能量正准备出发'}[state.mood];const lines=[`${spread[0].name}${spread[0].reversed?'逆位':''}读取着你此刻${tone}的情绪暗流。你选择的${state.drink}，像一枚落入水面的信号，让那些不易察觉的感受慢慢浮现。`,`当${spread[1].name}${spread[1].reversed?'逆位':''}来到行动的位置，它没有催促你立刻改变一切。它只提醒你，把注意力放回当下最值得被照顾的那一小部分。`,`${spread[2].name}${spread[2].reversed?'逆位':''}守望着今日尚未展开的风景。无需向未知索取答案，保留一点空间，回应会在你愿意倾听时出现。`];return lines}
async function getAiReading(spread){
  const payload={drink:state.drink,mood:state.mood,cards:spread.map(c=>({name:c.name,orientation:c.reversed?'逆位':'正位',role:c.role}))};
  try{const response=await fetch('/api/reading',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok) throw new Error('API unavailable');const data=await response.json();if(data.sections?.length===3)return data.sections}catch(error){console.warn('Using local fallback reading',error)}
  return makeReading(spread)
}
async function showResult(){const spread=draw();$('#revealBtn').disabled=true;$('#revealBtn').textContent='牌面正在回应…';const lines=await getAiReading(spread);$('#resultMeta').textContent=`${state.drink} · ${state.mood}`;$('#tarotSpread').innerHTML=spread.map(c=>`<article class="tarot-card ${c.reversed?'reverse':''}"><div class="tarot-inner"><div class="card-position">${c.role}</div><div class="card-symbol">${c.symbol}</div><div class="card-name">${c.name} ${c.reversed?'· 逆位':'· 正位'}</div></div></article>`).join('');$('#readingCopy').innerHTML=lines.map((x,i)=>`<div class="reading-block"><h3>${spread[i].role} · ${spread[i].name} ${spread[i].reversed?'逆位':'正位'}</h3><p>${x}</p></div>`).join('');$('#result').classList.remove('hidden');$('#result').scrollIntoView({behavior:'smooth'});window.currentText=`今日饮见 · ${state.drink} · ${state.mood}\n\n`+lines.join('\n\n');$('#revealBtn').textContent='让牌面回应我';$('#revealBtn').disabled=false}
function createShareImage(){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d');const g=ctx.createLinearGradient(0,0,1080,1350);g.addColorStop(0,'#312044');g.addColorStop(.5,'#120d1d');g.addColorStop(1,'#08070d');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1350);ctx.strokeStyle='rgba(215,179,106,.45)';ctx.lineWidth=2;ctx.strokeRect(46,46,988,1258);ctx.fillStyle='#d7b36a';ctx.font='28px serif';ctx.fillText('✦  今日饮见 · SIP & ARCANA',84,120);ctx.fillStyle='#f4ede4';ctx.font='48px serif';ctx.fillText(`${state.drink} · ${state.mood}`,84,210);ctx.font='34px serif';ctx.fillStyle='#d7b36a';ctx.fillText('今日三牌秘语',84,290);const cardNames=[...document.querySelectorAll('.card-name')].map(x=>x.textContent);cardNames.forEach((name,i)=>{ctx.fillStyle='#e4c995';ctx.font='30px serif';ctx.fillText(name,84,390+i*70)});ctx.fillStyle='#c6b9b8';ctx.font='26px serif';const words=(document.querySelector('.reading-block p')?.textContent||'让今天的回应，成为温柔的方向。').slice(0,90);words.match(/.{1,24}/g)?.forEach((line,i)=>ctx.fillText(line,84,700+i*48));ctx.fillStyle='#827681';ctx.font='20px serif';ctx.fillText('仅供娱乐与自我探索，不代表确定的未来预测。',84,1240);const link=document.createElement('a');link.download='今日饮见-分享.png';link.href=canvas.toDataURL('image/png');link.click()}
$('#revealBtn').addEventListener('click',showResult);$('#copyBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText(window.currentText||'');$('#copyBtn').textContent='已复制秘语 ✓';setTimeout(()=>$('#copyBtn').textContent='复制结果文案',1800)});$('#shareBtn').addEventListener('click',createShareImage);$('#restartBtn').addEventListener('click',()=>location.reload());
